services:
  - 'docker:dind'

image:build_prod:  
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  image: docker:stable
  script:
    - docker build -t $IMAGE_NAME /.
    - docker login -u "gitlab-ci-token" -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $IMAGE_NAME
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+.[0-9]+.[0-9]+$/
#  tags:
#    - prd

image:build_dev:  
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  image: docker:stable
  script:
    - docker build -t $IMAGE_NAME src/container/.
    - docker login -u "gitlab-ci-token" -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $IMAGE_NAME
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_COMMIT_TAG == null
#  tags:
#    - prd
